apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBGC+RQ/wdeoiLbMWGWhv8h/ND9Alo/b/11I1Te9nyh4kCKCWHvvRK5AvCOtWNCyDFzFF3+n7HTxW0qyuEhmVvMTdQUPLTygkiaj0m3HsnJbscx3TC9gpxcGBctx1HvWlohgIbQKP12BtL7g2I3A4njb7yrxObwmLURRZv7E/B48LTGgowoazR9J+oAZ8dkNzWlSOScswiOWHt3O166UdDnugEI4SrIt89aSiDSzIGl2rWHz2ncvPDyQGYoNTdWie//9paWQi+2Z/9PrSkNAp8Y0e3Bgl+f9gKsLSVPx3f5DbmMylu6IVwzoAw1GCCrMfOUdXUis1SJZirTKs9e1AF2Ac6212m+pWBCO1yt8CQjd4k5wxDAo2Apl9nImMoE6Y4R2RMebSKwe7CZqMWcx6ds3QpPxR5h+YDmfYipPbheAzJX5m75eZd9w3G21+tNNnJ7vnUhq7VvpJJ0tl+5Ig4Q4L0Z0McLo7j/KJtNV3CFuIXjmssDD0+sA3FiKhfo1ntd3XxUsvfjLs8t6a3D4l5l0fbhbMGNswF3sHKlMa0XCQ//JjZa6MK6/P6IIS6A3F8vxXDYrnVsdxlCaaxprazeUhnOohBRTGhXk09v9AAl+uMm0MrFqEU7vR1UnRZnIHn00znPJfztMQziVDFI5AHBXvFzvgyHcHDcO9Maqos63gN06qzJ/z/d3k9JTnF9EUWuk5CSw85HpQrHFY848Pc6RF+DaqEfcuUM2Iban2yG5s5l+jJsR0nKV3hPz4OwlUthh/8Ufthotlwg2wvL0CDI7F1W4RHE8WJt08OkjP7OXOH1/IoaPL1HuDWlsmBfv7dsdcqjFK37Xhz/OioTsZAzK2Zcwbg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

